site_name: Dmitry Mackaroff
site_author: Dmitry Mckaroff
site_url: https://mackaroff.com
site_description: >-
  Я помогаю маркетинговым командам развиваться и находить
  новые способы решения коммерческих задач используя научные подходы
  и технологические решения.
copyright: Steal like an artist @ 2024

theme:
  name: 'material'
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
  logo: media/favicon.png
  favicon: media/favicon.png
  language: ru
  features:
    - content.tooltips
    - navigation.next-prev
    - navigation.indexes
    - navigation.footer
    - navigation.expand
    - navigation.instant
  icon:
    annotation: material/arrow-right-circle

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/Mackaroff
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100058073734932
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dmitry-makarov-826176134?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BxGKF6kUpRRu1Ljbi0JZlWQ%3D%3D
    - icon: fontawesome/solid/envelope
      link: mailto:mackaroff@mackaroff.com

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/navicons.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/extra.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css

nav:
  - Home: about/CV.md
  - Основы:
    - Медиапланирование: basic-tools/media-planning-basics.md
    - Сегментация клиентов (RTB): basic-tools/Customer-Segmentation-(RTB).md
  - Инструменты CMO:
    - Матрица Хосин Канри: CMO-tools/hoshin-kanri-matrix.md
    - Семантический дифференциал: CMO-tools/semantic-differential.md
    - Оптимизация времени напоминания: CMO-tools/optimization-of reminders-for-periodic-services.md
    - Оптимизация медиаплана: CMO-tools/media-planning-optimization.md
  - Обо мне:
    - about/index.md
    - Опыт работы: about/employment-history.md
    - Проекты: about/projects.md
    - Принципы работы: about/work-principles.md
